apiVersion: v1
kind: Pod
metadata:
  name: pvcpod
spec:
  volumes:
    - name: pvcpod
      persistentVolumeClaim:
        claimName: pvctest
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: pvcpod
